validate-formatting:
  stage: validate_formatting
  image: debian:bookworm
  script:
    - ./firmware/ci.sh check-formatting

build-firmware:
   stage: build
   image: zephyrprojectrtos/ci:v0.26.5
   script:
    - ./firmware/ci.sh build-firmware
   artifacts:
     expire_in: 2 week
     paths:
       - firmware/build/zephyr/zephyr.bin
       - firmware/build/zephyr/zephyr.elf
       - firmware/build/zephyr/zephyr.hex
       - firmware/build/zephyr/zephyr.lst
       - firmware/build/zephyr/zephyr.map

test-firmware:
  stage: test
  image: debian:bookworm
  script:
    - PATH="/root/.local/bin:$PATH"
    - ./firmware/ci.sh test-firmware
